var tree = [["Eloquent",,"",
                [["Composer",,"",
                [["NpmBridge","Eloquent\/Composer\/NpmBridge.html","",
                [["Exception","Eloquent\/Composer\/NpmBridge\/Exception.html","",
                [["NpmCommandFailedException","Eloquent\/Composer\/NpmBridge\/Exception\/NpmCommandFailedException.html"," < Exception",
                [        ]],["NpmNotFoundException","Eloquent\/Composer\/NpmBridge\/Exception\/NpmNotFoundException.html"," < Exception",
                [        ]]        ]],["NpmBridge","Eloquent\/Composer\/NpmBridge\/NpmBridge.html","",
                [        ]],["NpmBridgeFactory","Eloquent\/Composer\/NpmBridge\/NpmBridgeFactory.html","",
                [        ]],["NpmBridgeFactoryInterface","Eloquent\/Composer\/NpmBridge\/NpmBridgeFactoryInterface.html","",
                [        ]],["NpmBridgeInterface","Eloquent\/Composer\/NpmBridge\/NpmBridgeInterface.html","",
                [        ]],["NpmBridgePlugin","Eloquent\/Composer\/NpmBridge\/NpmBridgePlugin.html","",
                [        ]],["NpmClient","Eloquent\/Composer\/NpmBridge\/NpmClient.html","",
                [        ]],["NpmClientInterface","Eloquent\/Composer\/NpmBridge\/NpmClientInterface.html","",
                [        ]],["NpmVendorFinder","Eloquent\/Composer\/NpmBridge\/NpmVendorFinder.html","",
                [        ]],["NpmVendorFinderInterface","Eloquent\/Composer\/NpmBridge\/NpmVendorFinderInterface.html","",
                [        ]]        ]]        ]]        ]]        ]

